# Generated by Django 4.1.5 on 2023-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
