# Generated by Django 4.1.5 on 2023-01-04 21:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_genres_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='music',
            field=models.FileField(upload_to='media/music_files', validators=[main.models.MusicModel.validate_file_extension]),
        ),
    ]
